begin;

-- Roles are intentionally stored outside public.profiles. Profiles are public
-- and self-editable, while these RBAC tables have no direct client mutations.
do $$
begin
  create type public.app_role as enum ('admin', 'moderator', 'user');
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.app_permission as enum (
    'dashboard.access',
    'platform.manage',
    'users.read',
    'users.manage',
    'roles.manage',
    'content.read_all',
    'reports.read',
    'reports.manage',
    'artworks.moderate',
    'moderation_log.read',
    'stats.read'
  );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.report_reason as enum (
    'spam',
    'harassment',
    'hate',
    'sexual',
    'violence',
    'copyright',
    'other'
  );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.report_status as enum (
    'open',
    'in_review',
    'resolved',
    'dismissed'
  );
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.moderation_action as enum (
    'report_marked_in_review',
    'report_resolved',
    'report_dismissed',
    'artwork_removed'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'user',
  assigned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.role_permissions (
  role public.app_role not null,
  permission public.app_permission not null,
  primary key (role, permission)
);

alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

-- Admin receives every elevated permission. A normal user deliberately has no
-- elevated permission rows; regular PixAnony access remains ownership-based RLS.
insert into public.role_permissions (role, permission)
select 'admin'::public.app_role, permission
from unnest(enum_range(null::public.app_permission)) as permission
on conflict do nothing;

insert into public.role_permissions (role, permission)
values
  ('moderator', 'dashboard.access'),
  ('moderator', 'reports.read'),
  ('moderator', 'reports.manage'),
  ('moderator', 'artworks.moderate'),
  ('moderator', 'moderation_log.read'),
  ('moderator', 'stats.read')
on conflict do nothing;

-- Existing accounts are backfilled as normal users. No account is silently
-- promoted during migration; the first admin must be explicitly assigned.
insert into public.user_roles (user_id, role)
select id, 'user'::public.app_role
from auth.users
on conflict (user_id) do nothing;

create or replace function public.has_permission(
  requested_permission public.app_permission
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles ur
    join public.role_permissions rp on rp.role = ur.role
    where ur.user_id = (select auth.uid())
      and rp.permission = requested_permission
  );
$$;

revoke all on function public.has_permission(public.app_permission) from public, anon;
grant execute on function public.has_permission(public.app_permission) to authenticated;

create or replace function public.get_my_access()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with current_access as (
    select coalesce(
      (select ur.role from public.user_roles ur where ur.user_id = (select auth.uid())),
      'user'::public.app_role
    ) as role
  )
  select jsonb_build_object(
    'role', current_access.role::text,
    'permissions', coalesce(
      jsonb_agg(rp.permission::text order by rp.permission::text)
        filter (where rp.permission is not null),
      '[]'::jsonb
    )
  )
  from current_access
  left join public.role_permissions rp on rp.role = current_access.role
  group by current_access.role;
$$;

revoke all on function public.get_my_access() from public, anon;
grant execute on function public.get_my_access() to authenticated;

create table if not exists public.role_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  previous_role public.app_role not null,
  new_role public.app_role not null,
  created_at timestamptz not null default now()
);

alter table public.role_audit_log enable row level security;

create policy "Admins can read role audit log"
  on public.role_audit_log for select to authenticated
  using ((select public.has_permission('roles.manage')));

create or replace function public.set_user_role(
  target_user_id uuid,
  target_role text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  acting_user_id uuid := (select auth.uid());
  previous_role public.app_role;
  resolved_role public.app_role;
begin
  if acting_user_id is null
    or not public.has_permission('roles.manage') then
    raise exception 'Insufficient permission to manage roles'
      using errcode = '42501';
  end if;

  if target_user_id = acting_user_id then
    raise exception 'You cannot change your own role'
      using errcode = '42501';
  end if;

  begin
    resolved_role := target_role::public.app_role;
  exception
    when invalid_text_representation then
      raise exception 'Invalid role';
  end;

  select ur.role into previous_role
  from public.user_roles ur
  where ur.user_id = target_user_id
  for update;

  if not found then
    raise exception 'User role record not found';
  end if;

  if previous_role = resolved_role then
    return;
  end if;

  update public.user_roles
  set role = resolved_role,
      assigned_by = acting_user_id,
      updated_at = now()
  where user_id = target_user_id;

  insert into public.role_audit_log (
    actor_id,
    target_user_id,
    previous_role,
    new_role
  )
  values (
    acting_user_id,
    target_user_id,
    previous_role,
    resolved_role
  );
end;
$$;

revoke all on function public.set_user_role(uuid, text) from public, anon;
grant execute on function public.set_user_role(uuid, text) to authenticated;

create or replace function public.get_dashboard_users(
  search_term text default null,
  result_limit integer default 50,
  result_offset integer default 0
)
returns table (
  user_id uuid,
  username text,
  display_name text,
  avatar_url text,
  is_verified boolean,
  created_at timestamptz,
  role text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.has_permission('users.read') then
    raise exception 'Insufficient permission to view users'
      using errcode = '42501';
  end if;

  return query
  select
    p.id,
    p.username,
    p.display_name,
    p.avatar_url,
    coalesce(p.is_verified, false),
    p.created_at,
    ur.role::text
  from public.profiles p
  join public.user_roles ur on ur.user_id = p.id
  where nullif(btrim(search_term), '') is null
    or p.username ilike '%' || btrim(search_term) || '%'
    or p.display_name ilike '%' || btrim(search_term) || '%'
  order by p.created_at desc
  limit least(greatest(coalesce(result_limit, 50), 1), 100)
  offset greatest(coalesce(result_offset, 0), 0);
end;
$$;

revoke all on function public.get_dashboard_users(text, integer, integer) from public, anon;
grant execute on function public.get_dashboard_users(text, integer, integer) to authenticated;

-- Extend the existing auth trigger so profile and default role creation are one
-- atomic operation for email and OAuth accounts alike.
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  base_username text;
  safe_username text;
begin
  base_username := lower(coalesce(
    new.raw_user_meta_data ->> 'preferred_username',
    new.raw_user_meta_data ->> 'user_name',
    split_part(coalesce(new.email, 'pixel_artist'), '@', 1)
  ));
  base_username := regexp_replace(base_username, '[^a-z0-9_]+', '_', 'g');
  base_username := trim(both '_' from base_username);
  if char_length(base_username) < 3 then
    base_username := 'pixel_artist';
  end if;

  safe_username := left(base_username, 30);
  if exists (select 1 from public.profiles where username = safe_username) then
    safe_username := left(base_username, 21) || '_' || left(replace(new.id::text, '-', ''), 8);
  end if;

  insert into public.profiles (id, username, display_name, avatar_url)
  values (
    new.id,
    safe_username,
    left(coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      nullif(new.raw_user_meta_data ->> 'name', ''),
      safe_username
    ), 80),
    coalesce(
      new.raw_user_meta_data ->> 'avatar_url',
      new.raw_user_meta_data ->> 'picture'
    )
  )
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

create table if not exists public.reports (
  id uuid primary key default extensions.uuid_generate_v4(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  artwork_id uuid references public.artworks(id) on delete set null,
  target_id uuid not null,
  target_owner_id uuid references public.profiles(id) on delete set null,
  reason public.report_reason not null,
  details text,
  status public.report_status not null default 'open',
  assigned_to uuid references public.profiles(id) on delete set null,
  resolved_by uuid references public.profiles(id) on delete set null,
  resolution_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint reports_details_length check (
    details is null or char_length(btrim(details)) between 1 and 2000
  ),
  constraint reports_resolution_note_length check (
    resolution_note is null or char_length(btrim(resolution_note)) between 1 and 2000
  ),
  constraint reports_target_consistency check (
    artwork_id is null or artwork_id = target_id
  )
);

alter table public.reports enable row level security;

create unique index if not exists reports_one_active_per_reporter
  on public.reports (reporter_id, target_id)
  where status in ('open', 'in_review');
create index if not exists reports_queue
  on public.reports (status, created_at desc);
create index if not exists reports_target
  on public.reports (target_id, created_at desc);

create or replace function private.prepare_artwork_report()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  artwork_owner_id uuid;
begin
  select a.user_id into artwork_owner_id
  from public.artworks a
  where a.id = new.artwork_id;

  if not found then
    raise exception 'Artwork not found';
  end if;

  if (select auth.uid()) is not null then
    new.reporter_id := (select auth.uid());
  end if;
  new.target_id := new.artwork_id;
  new.target_owner_id := artwork_owner_id;
  new.status := 'open';
  new.assigned_to := null;
  new.resolved_by := null;
  new.resolution_note := null;
  new.resolved_at := null;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.prepare_artwork_report() from public, anon, authenticated;
drop trigger if exists prepare_artwork_report on public.reports;
create trigger prepare_artwork_report
  before insert on public.reports
  for each row execute function private.prepare_artwork_report();

create policy "Users can create artwork reports"
  on public.reports for insert to authenticated
  with check (
    reporter_id = (select auth.uid())
    and status = 'open'
    and artwork_id is not null
    and exists (
      select 1
      from public.artworks a
      where a.id = reports.artwork_id
        and a.user_id <> (select auth.uid())
    )
  );

create policy "Users can read their own reports"
  on public.reports for select to authenticated
  using (reporter_id = (select auth.uid()));

create policy "Staff can read reports"
  on public.reports for select to authenticated
  using ((select public.has_permission('reports.read')));

-- Staff can see only the extra artwork rows required by their role. Admin sees
-- all content; moderators see non-public/private content only when it is reported.
create policy "Admins can read all artworks"
  on public.artworks for select to authenticated
  using ((select public.has_permission('content.read_all')));

create policy "Moderators can read reported artworks"
  on public.artworks for select to authenticated
  using (
    (select public.has_permission('reports.read'))
    and exists (
      select 1
      from public.reports r
      where r.target_id = artworks.id
        and r.status in ('open', 'in_review')
    )
  );

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action public.moderation_action not null,
  report_id uuid references public.reports(id) on delete set null,
  target_id uuid not null,
  target_owner_id uuid references public.profiles(id) on delete set null,
  note text,
  created_at timestamptz not null default now(),
  constraint moderation_action_note_length check (
    note is null or char_length(btrim(note)) between 1 and 2000
  )
);

alter table public.moderation_actions enable row level security;

create policy "Staff can read moderation activity"
  on public.moderation_actions for select to authenticated
  using ((select public.has_permission('moderation_log.read')));

create index if not exists moderation_actions_created
  on public.moderation_actions (created_at desc);
create index if not exists moderation_actions_target
  on public.moderation_actions (target_id, created_at desc);

create or replace function public.review_report(
  target_report_id uuid,
  decision text,
  note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  acting_user_id uuid := (select auth.uid());
  report_record public.reports%rowtype;
  action_name public.moderation_action;
  next_status public.report_status;
begin
  if acting_user_id is null
    or not public.has_permission('reports.manage') then
    raise exception 'Insufficient permission to manage reports'
      using errcode = '42501';
  end if;

  if note is not null and char_length(btrim(note)) > 2000 then
    raise exception 'Moderation note is too long';
  end if;

  select * into report_record
  from public.reports
  where id = target_report_id
  for update;

  if not found then
    raise exception 'Report not found';
  end if;

  if report_record.status in ('resolved', 'dismissed') then
    raise exception 'Report is already closed';
  end if;

  case decision
    when 'in_review' then
      next_status := 'in_review';
      action_name := 'report_marked_in_review';
    when 'resolved' then
      next_status := 'resolved';
      action_name := 'report_resolved';
    when 'dismissed' then
      next_status := 'dismissed';
      action_name := 'report_dismissed';
    else
      raise exception 'Invalid report decision';
  end case;

  update public.reports
  set status = next_status,
      assigned_to = acting_user_id,
      resolved_by = case when next_status in ('resolved', 'dismissed') then acting_user_id else null end,
      resolution_note = nullif(btrim(note), ''),
      resolved_at = case when next_status in ('resolved', 'dismissed') then now() else null end,
      updated_at = now()
  where id = target_report_id;

  insert into public.moderation_actions (
    actor_id,
    action,
    report_id,
    target_id,
    target_owner_id,
    note
  )
  values (
    acting_user_id,
    action_name,
    target_report_id,
    report_record.target_id,
    report_record.target_owner_id,
    nullif(btrim(note), '')
  );
end;
$$;

revoke all on function public.review_report(uuid, text, text) from public, anon;
grant execute on function public.review_report(uuid, text, text) to authenticated;

create or replace function public.moderate_artwork(
  target_artwork_id uuid,
  linked_report_id uuid default null,
  note text default null
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  acting_user_id uuid := (select auth.uid());
  artwork_owner_id uuid;
  can_manage_all boolean := public.has_permission('platform.manage');
  has_active_report boolean;
begin
  if acting_user_id is null
    or not public.has_permission('artworks.moderate') then
    raise exception 'Insufficient permission to remove artwork'
      using errcode = '42501';
  end if;

  if note is not null and char_length(btrim(note)) > 2000 then
    raise exception 'Moderation note is too long';
  end if;

  select a.user_id into artwork_owner_id
  from public.artworks a
  where a.id = target_artwork_id
  for update;

  if not found then
    return false;
  end if;

  select exists (
    select 1
    from public.reports r
    where r.target_id = target_artwork_id
      and r.status in ('open', 'in_review')
  ) into has_active_report;

  if not can_manage_all and not has_active_report then
    raise exception 'Moderators can remove only reported artwork'
      using errcode = '42501';
  end if;

  if linked_report_id is not null and not exists (
    select 1
    from public.reports r
    where r.id = linked_report_id
      and r.target_id = target_artwork_id
  ) then
    raise exception 'Report does not match the artwork';
  end if;

  update public.reports
  set status = 'resolved',
      assigned_to = coalesce(assigned_to, acting_user_id),
      resolved_by = acting_user_id,
      resolution_note = coalesce(nullif(btrim(note), ''), 'Artwork removed'),
      resolved_at = now(),
      updated_at = now()
  where target_id = target_artwork_id
    and status in ('open', 'in_review');

  insert into public.moderation_actions (
    actor_id,
    action,
    report_id,
    target_id,
    target_owner_id,
    note
  )
  values (
    acting_user_id,
    'artwork_removed',
    linked_report_id,
    target_artwork_id,
    artwork_owner_id,
    coalesce(nullif(btrim(note), ''), 'Artwork removed')
  );

  delete from public.artworks where id = target_artwork_id;
  return true;
end;
$$;

revoke all on function public.moderate_artwork(uuid, uuid, text) from public, anon;
grant execute on function public.moderate_artwork(uuid, uuid, text) to authenticated;

create or replace function public.get_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not public.has_permission('stats.read') then
    raise exception 'Insufficient permission to view platform statistics'
      using errcode = '42501';
  end if;

  result := jsonb_build_object(
    'open_reports', (select count(*) from public.reports where status = 'open'),
    'in_review_reports', (select count(*) from public.reports where status = 'in_review'),
    'resolved_reports', (select count(*) from public.reports where status = 'resolved'),
    'moderation_actions_30d', (
      select count(*)
      from public.moderation_actions
      where created_at >= now() - interval '30 days'
    )
  );

  if public.has_permission('platform.manage') then
    result := result || jsonb_build_object(
      'total_users', (select count(*) from public.profiles),
      'total_artworks', (select count(*) from public.artworks),
      'public_artworks', (select count(*) from public.artworks where visibility = 'public'),
      'total_likes', (select count(*) from public.likes)
    );
  end if;

  return result;
end;
$$;

revoke all on function public.get_dashboard_stats() from public, anon;
grant execute on function public.get_dashboard_stats() to authenticated;

revoke all on public.user_roles, public.role_permissions,
  public.role_audit_log, public.reports, public.moderation_actions
  from public, anon, authenticated;

grant usage on type public.app_role, public.app_permission,
  public.report_reason, public.report_status, public.moderation_action
  to authenticated;
grant select on public.role_audit_log, public.reports,
  public.moderation_actions to authenticated;
grant insert on public.reports to authenticated;

commit;
