begin;

alter table public.artworks
  alter column views_count set default 0;

update public.artworks
set views_count = 0
where views_count is null;

alter table public.artworks
  alter column views_count set not null;

create table if not exists public.artwork_views (
  id bigint generated by default as identity primary key,
  artwork_id uuid not null references public.artworks(id) on delete cascade,
  viewer_key text not null,
  created_at timestamptz not null default now(),
  constraint artwork_views_unique_viewer unique (artwork_id, viewer_key)
);

alter table public.artwork_views enable row level security;
revoke all on public.artwork_views from public, anon, authenticated;

create or replace function public.record_artwork_view(
  target_artwork_id uuid,
  anonymous_viewer_token text default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  viewer_id uuid := (select auth.uid());
  artwork_owner_id uuid;
  artwork_receiver_id uuid;
  artwork_visibility text;
  current_views integer;
  resolved_viewer_key text;
  inserted_rows integer := 0;
begin
  select user_id, receiver_id, visibility, views_count
  into artwork_owner_id, artwork_receiver_id, artwork_visibility, current_views
  from public.artworks
  where id = target_artwork_id;

  if not found then
    return null;
  end if;

  if not (
    artwork_visibility = 'public'
    or artwork_owner_id = viewer_id
    or artwork_receiver_id = viewer_id
  ) then
    return current_views;
  end if;

  -- A creator viewing their own artwork should not inflate its reach.
  if viewer_id is not null and viewer_id = artwork_owner_id then
    return current_views;
  end if;

  if viewer_id is not null then
    resolved_viewer_key := 'user:' || viewer_id::text;
  elsif anonymous_viewer_token is not null
    and char_length(anonymous_viewer_token) between 16 and 128 then
    resolved_viewer_key := 'anon:' || md5(anonymous_viewer_token);
  else
    return current_views;
  end if;

  insert into public.artwork_views (artwork_id, viewer_key)
  values (target_artwork_id, resolved_viewer_key)
  on conflict (artwork_id, viewer_key) do nothing;

  get diagnostics inserted_rows = row_count;

  if inserted_rows > 0 then
    update public.artworks
    set views_count = views_count + 1
    where id = target_artwork_id
    returning views_count into current_views;
  end if;

  return current_views;
end;
$$;

revoke all on function public.record_artwork_view(uuid, text) from public;
grant execute on function public.record_artwork_view(uuid, text) to anon, authenticated;

create index if not exists idx_artwork_views_created_at
  on public.artwork_views (artwork_id, created_at desc);

create index if not exists idx_notifications_user_read_created
  on public.notifications (user_id, read, created_at desc);

alter table public.notifications replica identity full;

create or replace function private.create_social_notification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  owner_id uuid;
  source_actor_id uuid;
  target_artwork_id uuid;
  notification_type text := case tg_table_name
    when 'likes' then 'like'
    when 'reposts' then 'repost'
    when 'comments' then 'comment'
    when 'follows' then 'follow'
  end;
begin
  if tg_op = 'DELETE' then
    -- Comment notifications are intentionally retained because one creator can
    -- leave multiple comments and the legacy table has no comment_id column.
    if tg_table_name = 'comments' then
      return old;
    end if;

    if tg_table_name = 'follows' then
      owner_id := old.following_id;
      source_actor_id := old.follower_id;
      target_artwork_id := null;
    else
      source_actor_id := old.user_id;
      target_artwork_id := old.artwork_id;
      select user_id into owner_id
      from public.artworks
      where id = target_artwork_id;
    end if;

    delete from public.notifications
    where user_id = owner_id
      and notifications.actor_id = source_actor_id
      and artwork_id is not distinct from target_artwork_id
      and type = notification_type;

    return old;
  end if;

  if tg_table_name = 'follows' then
    owner_id := new.following_id;
    source_actor_id := new.follower_id;
    target_artwork_id := null;
  else
    source_actor_id := new.user_id;
    target_artwork_id := new.artwork_id;
    select user_id into owner_id
    from public.artworks
    where id = target_artwork_id;
  end if;

  if owner_id is not null and owner_id <> source_actor_id then
    if notification_type in ('like', 'repost', 'follow') then
      delete from public.notifications
      where user_id = owner_id
        and notifications.actor_id = source_actor_id
        and artwork_id is not distinct from target_artwork_id
        and type = notification_type;
    end if;

    insert into public.notifications (user_id, actor_id, artwork_id, type)
    values (owner_id, source_actor_id, target_artwork_id, notification_type);
  end if;

  return new;
end;
$$;

drop trigger if exists notify_on_like on public.likes;
drop trigger if exists notify_on_repost on public.reposts;
drop trigger if exists notify_on_comment on public.comments;
drop trigger if exists notify_on_follow on public.follows;

create trigger notify_on_like
  after insert or delete on public.likes
  for each row execute function private.create_social_notification();
create trigger notify_on_repost
  after insert or delete on public.reposts
  for each row execute function private.create_social_notification();
create trigger notify_on_comment
  after insert or delete on public.comments
  for each row execute function private.create_social_notification();
create trigger notify_on_follow
  after insert or delete on public.follows
  for each row execute function private.create_social_notification();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end
$$;

commit;
